### ISSUE TITLE
Ae chú ý hôm nay là hạn cuối deadline

### ISSUE THREAD

**Issue by Zugor** [TTATTT/BOOKCOWM#4]
Như tiêu đề. Nếu ai còn vướng ở đâu, submit issue lên để cùng giải quyết.

**Comment by DucNTKMA** [comment]
Hiện tại còn một số vấn đề sau chưa giải quyết xong:
1: Chưa tìm được cách views data toàn bộ cả tuần nên hiện tại đang cho
views ra từng ngày, click vào ngày để hiện thì món ( ảnh )
2: Phần Login  người dùng vào thì cho chọn đồ ăn - gặp lỗi nếu tạo
supperuser thì sẽ có người dùng, nhưng khi check theo form user nhập vào
(trong DB đã  có người dùng ) khi check lại ra None
3: Phần order chư hoàn thành xong.
4: Thanh toán và xuất file chưa làm

Vào Th 6, 3 thg 4, 2020 vào lúc 08:31 Bui Tuan Anh <
notifications@github.com> đã viết:

**Comment by Zugor** [comment]
@DucNTKMA 
1. - Query toàn bộ Menu trong tuần lên trước  `menus = Menu.objects.filter(Menu_date__range=["2020-04-06", "2020-04-10"]))`
- Lấy list món ăn trong tưng menu
```
results = []
for menu in menus:
  listCourse = Course.objects.filter(menu_id=menu.id)
  results.append(listCourse)
```

2. Không cần login, người dùng chỉ cần nhập tên để đặt đồ

P/s: Sử dụng model Django còn yếu, cần luyện tập với nhiều project hơn nữa. Tuần sau hoàn thành nốt đi nhé!

**Comment by DucNTKMA** [comment]
Ok, tôi sẽ cố gắng khác phục phần đó và hoàn thành nốt trong tuần sau.
Thanks

Vào Th 7, 4 thg 4, 2020 vào lúc 18:59 Bui Tuan Anh <
notifications@github.com> đã viết:
